# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    #
    # Set the available vm boxes
    #

    # prefer custom images hosted on our cdn
    vm_boxes = {
        "trusty" => {
            "box" => "sysops-trusty-base-amd64-pydev-20160226.box",
            "box_url" => "https://sysops.wpc.edgecastcdn.net/00AC7B/apt/vagrant/trusty/sysops-trusty-base-amd64-pydev-20160226.box"
        }
    }

    # set some default behaviors
    config.vm.box_check_update = true
    config.vm.network "forwarded_port", guest: 22, host: rand(30000) + 1234

    #
    # Configure virtualbox provider settings
    #

    config.vm.provider "virtualbox" do |v|
        # speed up dns
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end

    #
    # VMs for cleanroom default tox builds and tox driven tests
    #

    config.vm.define "trusty_sandbox", primary: true, autostart: true do |the_box|
      # specify the base box
      the_box.vm.box = vm_boxes['trusty']['box']
      the_box.vm.box_url = vm_boxes['trusty']['box_url']

      # specify the hostname
      the_box.vm.hostname = "trusty-sandbox"
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/provision-vagrant-vm.yml"
      ansible.verbose = true
    end

end
